apiVersion: apps/v1
kind: Deployment
metadata:
      name: recreate1
      labels:
         name: recreate1
         app: recreate1
spec:
      template:
         metadata:
             name: nginx-recreate
             labels:
               name: rec2
               app: rec_2
         spec:
             containers:
               - name: rectej
                 image: httpd
      selector:
          matchLabels:
               app: rec_2
      strategy:
          type: Recreate
 


#Errors__    
#The Deployment "recreate_1" is invalid: 
#* metadata.name: Invalid value: "recreate_1": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
#* spec.template.spec.containers[0].name: Invalid value: "rec_tej": a DNS-1123 label must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?')
#[root@master kubernetes]# vim deploy_recreate.yml 
#[root@master kubernetes]# kubectl create -f deploy_recreate.yml 
#The Deployment "recreate_1" is invalid: metadata.name: Invalid value: "recreate_1": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
    
