apiVersion: v1
kind: Service
metadata:
     name: negative1
     labels:
        name: ness
        tag: v1
spec:
    type: NodePort
    clusterIP: 10.100.10.125 
    ports:
      - port: 80
        targetPort: 80
        #nodePort: 35000   #The Service "negative1" is invalid: spec.ports[0].nodePort: Invalid value: 35000: provided port is not in the valid range. The range of valid ports is 30000-32767"
        nodePort: 32355
        protocol: TCP       #by default it gives TCP.
    selector:
         name: atom
