apiVersion: v1
kind: ReplicationController
metadata:
    name: my-rp1
    labels:
      name: myaaprp
      app: front-end
spec: 
    template:
      metadata:
         name: my
         labels:
           app: front-end
           name: appmy
      spec:
         containers:
           - image: nginx
             name: my-nginx
    replicas: 3 

 
