apiVersion: v1
kind: ReplicationController
metadata:
    name: my-rp
    labels:
      name: myaaprp
      app: front-end
spec: 
    template:
      metadata:
         name: my-app
         labels:
           app: front-end
           name: app
      spec:
         containers:
           - image: nginx
             name: my-nginx
    replicas: 3 

 
