apiVersion: v1
kind: Service
metadata:
     name: server
     labels:
        name: server1
        test: test1
spec:
   type: NodePort
   ports:
     - port: 80
       protocol: TCP
       nodePort: 3232
   clusterIP: 10.96.10.125
   replicas: 1
   selector:
       name: round1
---
apiVersion: apps/v1
kind: Deployment
metadata:
      name: dev1
      labels:
         name: dep1
         app: 
spec:
      template:
         metadata:
             name: nginx-2
             labels:
               name: r2
               app: r2
         spec:
             containers:
               - name: tej
                 image: httpd
      selector:
          matchLabels:
               name: r2
      strategy:
          type: Recreate
